name: build-mfem

on:
  push:

env:
  HYPRE_ARCHIVE: v2.19.0.tar.gz
  HYPRE_URL: https://github.com/hypre-space/hypre/archive
  HYPRE_TOP_DIR: hypre-2.19.0
  METIS_ARCHIVE: metis-4.0.3.tar.gz
  METIS_URL: https://mfem.github.io/tpls
  METIS_TOP_DIR: metis-4.0.3

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        MPI: ["NO", "YES"]
    env:
      MPI: ${{ matrix.MPI }}

    steps:
    - name: checkout MFEM
      uses: actions/checkout@v2
      with:
        path: mfem

    - name: Get MPI
      if: matrix.MPI == "YES"
      run: sudo apt-get install mpich libmpich-dev

    - name: Cache Hypre Install
      id: hypre-cache
      uses: actions/cache@v2
      with:
        path: ${{ env.HYPRE_TOP_DIR }}
        key: ${{ runner.os }}-build-${{ env.HYPRE_TOP_DIR }}-${{ matrix.MPI }}

    - name: Install Hypre
      if: matrix.MPI == "YES" && steps.hypre-cache.outputs.cache-hit != 'true'
      run: |
        wget --no-verbose ${HYPRE_URL}/${HYPRE_ARCHIVE};
        rm -rf ${HYPRE_TOP_DIR};
        tar -xzf ${HYPRE_ARCHIVE};
        cd ${HYPRE_TOP_DIR}/src;
        ./configure --disable-fortran CC=mpicc CXX=mpic++;
        make -j3;
        cd ../..;

    - name: Cache Metis Install
      id: metis-cache
      uses: actions/cache@v2
      with:
        path: ${{ env.METIS_TOP_DIR }}
        key: ${{ runner.os }}-build-${{ env.METIS_TOP_DIR }}-${{ matrix.MPI }}

    - name: Install Metis
      if: matrix.MPI == "YES" && steps.metis-cache.outputs.cache-hit != 'true'
      run: |
        wget --no-verbose ${METIS_URL}/${METIS_ARCHIVE};
        rm -rf ${METIS_TOP_DIR};
        tar -xzf ${METIS_ARCHIVE};
        make -j3 -C ${METIS_TOP_DIR}/Lib CC=mpicc OPTFLAGS="-O2";

    - name: configure
      run: |
        echo "Hypre symlink:"
        ln -s $HYPRE_TOP_DIR hypre;
        echo "Metis symlink:"
        ln -s $METIS_TOP_DIR metis-4.0;
        cd mfem
        make config MFEM_USE_MPI=$MPI
    - name: make
      run: |
        cd mfem
        make -j3
    - name: check
      run: |
        cd mfem
        make check
    - name: unit
      run: |
        cd mfem
        echo "make unittest"
    - name: test
      run: |
        cd mfem
        echo "make test"
