name: build-mfem

on:
  push:

env:
  HYPRE_ARCHIVE: v2.19.0.tar.gz
  HYPRE_URL: https://github.com/hypre-space/hypre/archive
  HYPRE_TOP_DIR: hypre-2.19.0
  METIS_ARCHIVE: metis-4.0.3.tar.gz
  METIS_URL: https://mfem.github.io/tpls
  METIS_TOP_DIR: metis-4.0.3

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        MPI: ["NO", "YES"]
    env:
      MPI: ${{ matrix.MPI }}

    steps:
    - name: checkout MFEM
      uses: actions/checkout@v2
      with:
        path: mfem

    - name: Get MPI
      run: |
        if [[ ${MPI} == "YES" ]]; then
          sudo apt-get install mpich libmpich-dev
        fi

    - name: Cache Hypre Install
      uses: actions/cache@v2
      with:
        path: ${{ env.HYPRE_TOP_DIR }}
        key: ${{ runner.os }}-build-${{ env.HYPRE_TOP_DIR }}-${{ matrix.MPI }}

    - name: Install Hypre
      run: |
        if [[ ${MPI} == "YES" ]]; then
           if [[ ! -e ${HYPRE_TOP_DIR}/src/hypre/lib/libHYPRE.a ]]; then
              wget --no-verbose ${HYPRE_URL}/${HYPRE_ARCHIVE};
              rm -rf ${HYPRE_TOP_DIR};
              tar -xzf ${HYPRE_ARCHIVE};
              cd ${HYPRE_TOP_DIR}/src;
              ./configure --disable-fortran CC=mpicc CXX=mpic++;
              make -j3;
              cd ../..;
           else
               echo "Reusing cached $HYPRE_TOP_DIR/";
           fi;
           ln -s $HYPRE_TOP_DIR hypre;
           echo "pwd: $(pwd)"
           echo "ls: $(ls)"
        else
           echo "Serial build, not using hypre";
        fi

    - name: Cache Metis Install
      uses: actions/cache@v2
      with:
        path: ${{ env.METIS_TOP_DIR }}
        key: ${{ runner.os }}-build-${{ env.METIS_TOP_DIR }}-${{ matrix.MPI }}

    - name: Install Metis
      run: |
        if [[ ${MPI} == "YES" ]]; then
           if [[ ! -e ${METIS_TOP_DIR}/libmetis.a ]]; then
              wget --no-verbose ${METIS_URL}/${METIS_ARCHIVE};
              rm -rf ${METIS_TOP_DIR};
              tar -xzf ${METIS_ARCHIVE};
              make -j3 -C ${METIS_TOP_DIR}/Lib CC=mpicc OPTFLAGS="-O2";
           else
               echo "Reusing cached $METIS_TOP_DIR/";
           fi;
           ln -s $METIS_TOP_DIR metis-4.0;
           echo "pwd: $(pwd)"
           echo "ls: $(ls)"
        else
           echo "Serial build, not using metis";
        fi

    - name: configure
      run: |
        cd mfem
        make config MFEM_USE_MPI=$MPI
    - name: make
      run: |
        cd mfem
        make -j3
    - name: check
      run: |
        cd mfem
        make check
    - name: unit
      run: |
        cd mfem
        echo "make unittest"
    - name: test
      run: |
        cd mfem
        echo "make test"
