name: build-mfem

on:
  push:

env:
  HYPRE_ARCHIVE: v2.19.0.tar.gz
  HYPRE_URL: https://github.com/hypre-space/hypre/archive
  HYPRE_TOP_DIR: hypre-2.19.0
  METIS_ARCHIVE: metis-4.0.3.tar.gz
  METIS_URL: https://mfem.github.io/tpls
  METIS_TOP_DIR: metis-4.0.3

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        MPI: ["NO", "YES"]
    env:
      MPI: ${{ matrix.MPI }}

    steps:
    # Checkout MFEM in "mfem" subdirectory. Final path: /home/runner/work/mfem/mfem/mfem
    - name: checkout MFEM
      uses: actions/checkout@v2
      with:
        path: mfem

    # Only get mpi if defined for the job.
    - name: Get MPI
      if: matrix.MPI == 'YES'
      run: sudo apt-get install mpich libmpich-dev

    # Get Hypre through cache, or install it.
    # Install will only run on cache miss.
    - name: Get Hypre
      if: matrix.MPI == 'YES'
      uses: ./mfem/.github/actions/install-hypre

    # Get Metis through cache, or install it.
    # Install will only run on cache miss.
    - name: Cache Metis Install
      id: metis-cache
      uses: actions/cache@v2
      with:
        path: ${{ env.METIS_TOP_DIR }}
        key: ${{ runner.os }}-build-${{ env.METIS_TOP_DIR }}-${{ matrix.MPI }}

    - name: Install Metis
      if: matrix.MPI == 'YES' && steps.metis-cache.outputs.cache-hit != 'true'
      run: |
        wget --no-verbose ${METIS_URL}/${METIS_ARCHIVE};
        rm -rf ${METIS_TOP_DIR};
        tar -xzf ${METIS_ARCHIVE};
        make -j3 -C ${METIS_TOP_DIR}/Lib CC=mpicc OPTFLAGS="-O2";

    # MFEM build and test
    - name: configure
      run: |
        echo "Hypre symlink:"
        ln -s $HYPRE_TOP_DIR hypre;
        echo "Metis symlink:"
        ln -s $METIS_TOP_DIR metis-4.0;
        cd mfem
        make config MFEM_USE_MPI=$MPI MFEM_MPI_NP=2
    - name: make
      run: |
        cd mfem
        make -j3
    - name: check
      run: |
        cd mfem
        make check
    - name: unit
      run: |
        cd mfem
        make unittest
    - name: test
      run: |
        cd mfem
        make test
